# conda env create -f environment.yml
# https://nbgitpuller.readthedocs.io/en/latest/link.html?tab=binder

name: im4nis-workshop-env

channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.9, <=3.11
  - nbgitpuller
  - pandas
  - geopandas
  - contextily
  - numpy
  - matplotlib
  - ipympl
  - scikit-learn==1.1.3
  - scipy
  - umap-learn
  - sympy
  - joblib
  - requests
  - jupyter
  - jupyterlab
  - pyrolite
  - openpyxl
  - dtreeviz
